table FactSales
	lineageTag: 4224e16b-1b5f-5ba3-8637-0227ba7cad3f

	column OrderKey
		dataType: int64
		summarizeBy: none
		sourceColumn: OrderKey
		lineageTag: 0afd7ab4-aa71-5ddc-afd7-197bcc6f514b

	column LineNumber
		dataType: int64
		summarizeBy: none
		sourceColumn: LineNumber
		lineageTag: 172f8fa7-30c6-513f-90f8-5980588cd1c9

	column OrderDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		summarizeBy: none
		sourceColumn: OrderDate
		lineageTag: d9db84fe-a63e-596d-b723-6aa280ef8213

	column DeliveryDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		summarizeBy: none
		sourceColumn: DeliveryDate
		lineageTag: 0097fc86-8642-57ff-a969-af069128c012

	column CustomerKey
		dataType: int64
		summarizeBy: none
		sourceColumn: CustomerKey
		lineageTag: 804eec7a-421f-57b3-afe3-2d022ba53452

	column StoreKey
		dataType: int64
		summarizeBy: none
		sourceColumn: StoreKey
		lineageTag: d539fcbb-d1e7-5490-879b-acc1e92fa4dd

	column ProductKey
		dataType: int64
		summarizeBy: none
		sourceColumn: ProductKey
		lineageTag: e1713dc9-5c8e-53ea-bcdb-251ac2c13840

	column Channel
		dataType: string
		summarizeBy: none
		sourceColumn: Channel
		lineageTag: 36ac4ebe-fea7-5f10-b608-31cd4b5db498

	column Quantity
		dataType: int64
		summarizeBy: none
		sourceColumn: Quantity
		lineageTag: f52fd07f-6b26-5188-88fc-828c0a824267

	column UnitPrice
		dataType: double
		summarizeBy: none
		sourceColumn: UnitPrice
		lineageTag: 07543793-9893-58a1-aac6-7945a1cf3078

	column NetPrice
		dataType: double
		summarizeBy: none
		sourceColumn: NetPrice
		lineageTag: d941a76e-6197-53bb-967d-4ca88bfe8a25

	column UnitCost
		dataType: double
		summarizeBy: none
		sourceColumn: UnitCost
		lineageTag: a34cd02b-4c2c-55e4-9481-93d1c605b04d

	column CurrencyCode
		dataType: string
		summarizeBy: none
		sourceColumn: CurrencyCode
		lineageTag: 4a51408c-127f-51fc-8964-8d72aafe8c45

	column ExchangeRate
		dataType: double
		summarizeBy: none
		sourceColumn: ExchangeRate
		lineageTag: 88b524fe-4ddb-5952-b03f-7295c6f8e780

	partition FactSales = m
		mode: import
		source =
				let
					Source = Sql.Database("localhost\SQLEXPRESS", "ContosoRetail"),
					Data = Source{[Schema="dbo", Item="FactSales"]}[Data],
					Typed = Table.TransformColumnTypes(Data, {{"OrderDate", type date}, {"DeliveryDate", type date}}, "en-US")
				in
					Typed
